apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: syvbvxo95-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:3470c0007c56618d4c21dfe92e9ca1a2bc1aa6f1@sha256:672e71b92803be36025aebb253d0523d8e636a996118484bd8fdbf6622ac37d0
          name: container-image
